name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build_binary:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310

    steps:
    - uses: actions/checkout@v2

    - name: Build Python wheels
      with:
        python-version: ${{ matrix.python-version }}
        run: |
          docker run --rm -v `pwd`:/app quay.io/pypa/manylinux_2_24_x86_64 /app/entrypoint.sh

    - uses: actions/upload-artifact@v2
      with:
        path: ${{ GITHUB_WORKSPACE }}/dist/*.whl

  build_source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python setup.py sdist

    - uses: actions/upload-artifact@v2
      with:
        path: ${{ GITHUB_WORKSPACE }}/dist/*.whl

  publish:
    needs: [build_binary, build_source]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        path: ${{ GITHUB_WORKSPACE }}/dist/

    - name: Publish package to PyPI
      # All files in dist/ are published
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
